apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: spring-boot-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: spring-boot-app-manifests
    repoURL: "https://github.com/SallyNader/cicd-gitops.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true